language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - curl -s getcomposer.org/installer | php -d detect_unicode=Off
  - php composer.phar install --dev --prefer-source --no-interaction
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "short_open_tag = On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini


before_script:
  - ./bin/console doctrine:database:create --if-not-exists --env travis

script:
  - ./scripts/phpcs.sh
  - ./scripts/runtests.sh
