services:
  gotcms.repos:
    class: GotCms\Bundle\ApiBundle\Service\RepositoryService
    calls:
      - [ setContainer,[ "@service_container" ] ]
  gotcms.services:
    class: GotCms\Bundle\ApiBundle\Service\ServicesService
    calls:
      - [ setContainer,[ "@service_container" ] ]
